spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/triprider
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # ë˜ëŠ” validate, ê°œë°œ ì¤‘ì´ë¼ë©´ create ìœ ì§€ ê°€ëŠ¥
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        archive.autodetection: none  # ğŸ”¥ ì™¸ë¶€ ë¼ì´ë¸ŒëŸ¬ë¦¬ Entity ë¬´ì‹œ ì„¤ì •

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 316137395420-ig547fms4sva0jaoup5odgldfqhf36o4.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          kakao:
            client-id: 471ee3eec0b9d8a5fc4eb86fb849e524
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

course:
  path: classpath:/course   # ê°œë°œ ì¤‘ì—ëŠ” classpath ì‚¬ìš© -> ë°°í¬ ì‹œì— ì™¸ë¶€ íŒŒì¼ë¡œ ì´ë™ ì˜ˆì •

tourapi:
  base-url: "https://apis.data.go.kr/B551011/KorService2"
  service-key: "iQo2RqyJxO6Aq9UoLG3zi4v597yqgmlux9hm4Rr0GJ1FtlyXr0wEQAeO4eJWr6x7u2tbn3ZoVyzH1/bhUWRZ6g=="   # í¼ì„¼íŠ¸ ì¸ì½”ë”©ëœ ì„œë¹„ìŠ¤í‚¤
  mobile-os: "ETC"
  mobile-app: "TripRider"

weather:
  api:
    base-url: "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
    service-key: "B9lcEXU87CZ1bElz2TDsg24h3MrLRNIvSaS3U3tJadZevbVF15IegPFce577ni1sQSNvFEueuKIwO0wQcAd4tQ=="

logging:
  level:
    org.hibernate.SQL: debug
